### ISSUE TITLE
Error using this library with Botkit. 

### ISSUE THREAD

**Issue by donovat** [mbarlock/botkit-storage-couchdb#10]
I have included the botkit-storage-couchdb repo in my code, but once the code starts I get the following errors;
 /home/vcap/app/node_modules/botkit-storage-couchdb/lib/storage.js:85
         db.insert(design.doc, `_design/${design.namespace}`);
 [APP/PROC/WEB/0]ERR            ^
 TypeError: db.insert is not a function
     at designDocs.forEach.design (/home/vcap/app/node_modules/botkit-storage-couchdb/lib/storage.js:85:12)
     at Array.forEach (native)
     at module.exports.config (/home/vcap/app/node_modules/botkit-storage-couchdb/lib/storage.js:84:16)
     at Object.<anonymous> (/home/vcap/app/bot-facebook.js:25:55)
     at Module._compile (module.js:577:32)
     at Object.Module._extensions..js (module.js:586:10)
     at Module.load (module.js:494:32)
     at tryModuleLoad (module.js:453:12)
     at Function.Module._load (module.js:445:3)
     at Module.require (module.js:504:17)
     at require (internal/module.js:20:19)
     at module.exports (/home/vcap/app/app.js:32:18)
     at Object.<anonymous> (/home/vcap/app/server.js:38:17)
     at Module._compile (module.js:577:32)
     at Object.Module._extensions..js (module.js:586:10)
     at Module.load (module.js:494:32)
 Exit status 1

I am running the code on IBM's Cloud, and looking to test if I can use this repo code to connect to IBM's version of a couchdb - Cloudant. 
Also, how do you define usernames and passwords for connection to the db instance? 
Thanks.

**Comment by barlock** [comment]
I haven't touched this in a while so I'm not sure if `nano` or cloudant/couch have changed in api. 

You can pass credentials in the options. It passes them directly to nano https://github.com/apache/nano#configuration

**Comment by donovat** [comment]
I did take a look at the code, but there seems to be very little that I could see relating to nano or couchdb calls. 
Do you plan to look at the code, and determine if it is due to api changes?

**Comment by barlock** [comment]
I don't, I don't work at IBM anymore and so don't use couch. I've also changed away from Botkit as it (at least a year ago) had a tendency to break. 

This is my preferred library: https://github.com/MissionsAI/slapp

I believe there are some bots using it at github.ibm.com/whitewater if you want examples.
